export enum AuditEntityType {
  PLATFORM_USER = 'PLATFORM_USER',
  PLATFORM_ROLE = 'PLATFORM_ROLE',
  COMPANY = 'COMPANY',
  COMPANY_CONTACT = 'COMPANY_CONTACT',
  COMPANY_VERTICAL = 'COMPANY_VERTICAL',
  PLAN = 'PLAN',
  SUBSCRIPTION = 'SUBSCRIPTION',
  ORDER = 'ORDER',
  VERTICAL_TENANT = 'VERTICAL_TENANT',
  INVITE = 'INVITE',
  VERTICAL = 'VERTICAL',
}