export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  SUSPEND = 'SUSPEND',
  ACTIVATE = 'ACTIVATE',
  CANCEL = 'CANCEL',
  PROVISION = 'PROVISION',
  FAIL = 'FAIL',
  SEND_INVITE = 'SEND_INVITE',
  RESEND_INVITE = 'RESEND_INVITE',
  REVOKE_INVITE = 'REVOKE_INVITE',
  LOGIN = 'LOGIN',
}